"use client";

import { useState } from "react";

export default function Examples() {
  const [playingVideo, setPlayingVideo] = useState<number | null>(null);

  const examples = [
    {
      id: 1,
      title: "Dynamic Particle System",
      description: "Flowing particles with smooth motion trails",
      videoUrl: "/videos/1111111111.mp4",
    },
    {
      id: 2,
      title: "Geometric Morphing",
      description: "Shapes transforming with elegant transitions",
      videoUrl: "/videos/2222222222.mp4",
    },
    {
      id: 3,
      title: "Wave Animation",
      description: "Smooth wave effects with gradient colors",
      videoUrl: "/videos/3333333333.mp4",
    },
  ];

  return (
    <section className="py-16 px-4 relative">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
            See What Others Created with RiftRunner
          </h2>
          <p className="text-lg text-gray-400 max-w-2xl mx-auto">
            Real animations generated by our users. Get inspired and create your own!
          </p>
        </div>

        <div className="grid md:grid-cols-3 gap-6">
          {examples.map((example) => (
            <div
              key={example.id}
              className="group bg-white/5 backdrop-blur-lg rounded-xl border border-white/10 overflow-hidden hover:border-purple-500/50 transition-all duration-300"
            >
              {/* 视频播放区域 */}
              <div className="relative aspect-video bg-gradient-to-br from-purple-900/20 to-pink-900/20 overflow-hidden">
                <video
                  className="w-full h-full object-cover"
                  loop
                  muted
                  playsInline
                  autoPlay
                  onMouseEnter={(e) => e.currentTarget.play()}
                  onMouseLeave={(e) => e.currentTarget.pause()}
                >
                  <source src={example.videoUrl} type="video/mp4" />
                  Your browser does not support the video tag.
                </video>

                {/* 悬停时显示播放图标提示 */}
                <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-all duration-300 flex items-center justify-center pointer-events-none">
                  <div className="opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                    <svg
                      className="w-12 h-12 text-white drop-shadow-lg"
                      fill="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path d="M8 5v14l11-7z" />
                    </svg>
                  </div>
                </div>
              </div>

              {/* 案例信息 */}
              <div className="p-6">
                <h3 className="text-xl font-bold text-white mb-2">{example.title}</h3>
                <p className="text-gray-400 text-sm">{example.description}</p>
              </div>
            </div>
          ))}
        </div>

        {/* CTA */}
        <div className="text-center mt-12">
          <p className="text-gray-400 mb-4">Ready to create your own animation?</p>
          <button
            onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}
            className="bg-gradient-purple hover:opacity-90 text-white px-8 py-3 rounded-xl font-semibold transition-all duration-200 inline-flex items-center gap-2"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M5 10l7-7m0 0l7 7m-7-7v18"
              />
            </svg>
            Try RiftRunner Now
          </button>
        </div>
      </div>
    </section>
  );
}
